version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tasks
    ports:
      - '5432:5432'

  app:
    container_name: todo-list
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:808'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/tasks
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db